### ISSUE TITLE
Add linear search

### ISSUE THREAD

**Issue by jsparmani** [developer-student-club-thapar/algo-book#32]

**Comment by desai10** [comment]
Sure, !'ll take this up!

**Comment by jsparmani** [comment]
@desai10 Sure
Here are the requirements for an acceptable PR for the same.
**Languages for the algorithms**:
1. Python
2. C++
3. Java
4. Javascript
5. `README.md` file with explanation of the algorithm

**Comment by desai10** [comment]
@jsparmani ya sure, got it.

**Comment by Khush-Ramdev** [comment]
can is also contribute?
I can write in C++ and javascript

**Comment by ayushvrma** [comment]
Yeah sure you can give it to me!
