### ISSUE TITLE
Add binary search

### ISSUE THREAD

**Issue by jsparmani** [developer-student-club-thapar/algo-book#33]

**Comment by Gautam-virmani** [comment]
can I do this task

**Comment by suntansoker** [comment]
Hi, I'll be working on the binary search

**Comment by jsparmani** [comment]
Sure @Gautam-virmani and @suntansoker you guyz can contribute for this specific algorithm.
Here are the requirements for an acceptable PR for the same.
**Languages for the algorithms**:
1. Python
2. C++
3. Java
4. Javascript
5. `README.md` file with explanation of the algorithm

**Comment by Renu-code** [comment]
Can I implement the binary search either in Python/Java??

**Comment by Gautam-virmani** [comment]
I have done it already , you can review and merge if there is no problem .

**Comment by gaurav-codehub** [comment]
Can I implement the binary search in C++?

**Comment by DakshKK** [comment]
> I have done it already , you can review and merge if there is no problem .

@Gautam-virmani 

Please refer to the [contribution guidelines](https://github.com/developer-student-club-thapar/algo-book/blob/master/CONTRIBUTING.md), and refer to the instructions about referring the issue in your PR, and ensure there are no duplicate implementations.

**Comment by Gautam-virmani** [comment]
So I have to make pull request again with change in fork. Copy of  read me .

**Comment by Gautam-virmani** [comment]
Hey@DakshKK, I have done the task already 8 days back and you did not merge it, I have even updated the read me and now there is someone else binary search file is there.

**Comment by DakshKK** [comment]
Your PR was not merged since the [contribution guidelines](https://github.com/developer-student-club-thapar/algo-book/blob/master/CONTRIBUTING.md) were not followed, and that PR was opened before yours.

You can still implement the algorithm in any language you prefer, if it is a language that is already there, please ensure that your implementation is different else your PR will be closed again.
