### ISSUE TITLE
Add Selection sort algorithm

### ISSUE THREAD

**Issue by specter25** [developer-student-club-thapar/algo-book#40]

**Comment by saiharsha-22** [comment]
@specter25 Can you please assign this task to me I would like to contribute.

**Comment by shreyraj2002** [comment]
I would like to contribute to this issue, please assign this task to me.

**Comment by Renu-code** [comment]
I can implement the selection sort algorithm..can I work on this issue??

**Comment by specter25** [comment]
@shreyraj2002 and @Renu-code  in which language will you contribute ?

**Comment by citReyJoshua** [comment]
Can you assign this task to me? I'll implement with c++, js, python and java

**Comment by shreyraj2002** [comment]
> @shreyraj2002 and @Renu-code in which language will you contribute?

I can contribute in C, C++, Python, Java

**Comment by specter25** [comment]
@shreyraj2002 make a new folder name selection_sort inside the algorithms folder . And write the Java code ina file inside it . I am assigning this task to u .update me as soon as you are done .

**Comment by specter25** [comment]
@citReyJoshua  @Renu-code ,@saiharsha-22 you can contribute after @shreyraj2002 is done with the task

**Comment by specter25** [comment]
@sai-harsha-22 you can write the C code .
@citReyJoshua you can write the python code .
@Renu-code you can write the c++ code .

**Comment by citReyJoshua** [comment]
will do, thanks

**Comment by Renu-code** [comment]
@specter25 okay, thanks...I will implement in c++

**Comment by citReyJoshua** [comment]
@specter25 done with the python code

**Comment by Renu-code** [comment]
@specter25 Done with the c++ code..please review it #48

**Comment by specter25** [comment]
@citReyJoshua and @Renu-code  you had to do the task after @shreyraj2002 was done completing his task .

**Comment by shreyraj2002** [comment]
I have completed my assigned task @specter25 give it a review!

**Comment by shreyraj2002** [comment]
> @shreyraj2002 make a new folder name selection_sort inside the algorithms folder . And write the Java code ina file inside it . I am assigning this task to u .update me as soon as you are done .

I m done!
