### ISSUE TITLE
Add Insertion Sort

### ISSUE THREAD

**Issue by pranavvidyarthi7** [developer-student-club-thapar/algo-book#53]

**Comment by pranavvidyarthi7** [comment]
Here are the requirements for an acceptable PR for the same.
Languages for the algorithms:

- Python
- C++
- Java
- Javascript
- README.md file with explanation of the algorithm

**Comment by malhotraravi842** [comment]
I would like to work on this in c++.

**Comment by togami2864** [comment]
Hello! I want to work on this issue in python.

**Comment by pranavvidyarthi7** [comment]
Sure
@malhotraravi842 and @togami2864  we have already created a folder for Insertion sort 
Both of you can write your code in respective languages and raise a PR for the same

**Comment by harshithq** [comment]
Hola! I want to on this in Java

**Comment by pranavvidyarthi7** [comment]
Sure just write the code and create a PR

**Comment by Jasneet410** [comment]
Can I write the code in JavaScript

**Comment by pranavvidyarthi7** [comment]
Sure @Jasneet410

**Comment by pranavvidyarthi7** [comment]
Anyone up for writing the readme file for Insertion Sort?

**Comment by malhotraravi842** [comment]
I've added the readme file, just review it #57

**Comment by togami2864** [comment]
I've added python code. Please review it #61
