### ISSUE TITLE
Armstrong Number 

### ISSUE THREAD

**Issue by dragonman164** [developer-student-club-thapar/algo-book#58]
I would like to add code for Armstrong Number in C, C++ and Python

**Comment by specter25** [comment]
Here are the requirements for an acceptable PR for the same.
Languages for the algorithms:
1. Python
2. C++
3. Java
4. Javascript
5. README.md file with explanation of the algorithm

**Comment by dragonman164** [comment]
Ok

**Comment by ayushvrma** [comment]
I would love to do this!

**Comment by Yash7818** [comment]
hey! may i do this , i would love to

**Comment by pranavvidyarthi7** [comment]
yes you all can do it 
@dragonman164  besides python and c++ are you doing it in any other language?
If not then @Yash7818 and @ayushvrma  you both can decide and choose from Java or Javascript and upload the respective code inside the Armstrong Number folder already present there in algorithms folder

**Comment by ayushvrma** [comment]
@pranavvidyarthi7 no permission to push files

**Comment by pranavvidyarthi7** [comment]
first of all you have to fork this repo and then make changes at your end 
When you will push the code you will be able to create a PR from your repo to ours
@ayushvrma

**Comment by dragonman164** [comment]
I am doing in Python and C++ only

**Comment by Yash7818** [comment]
#70

**Comment by Yash7818** [comment]
**armstrong.js added** #70

**Comment by KuKikb** [comment]
I would like write an algorithm  for this in python.

**Comment by Anuragkar234** [comment]
> Here are the requirements for an acceptable PR for the same.
> Languages for the algorithms:
> 
> 1. Python
> 2. C++
> 3. Java
> 4. Javascript
> 5. README.md file with explanation of the algorithm

Is golang acceptable?

**Comment by KuKikb** [comment]
do I fork right now or wait for someone to assign or one issue can only be assigned to one person?

**Comment by DakshKK** [comment]
> > Here are the requirements for an acceptable PR for the same.
> > Languages for the algorithms:
> > 
> > 1. Python
> > 2. C++
> > 3. Java
> > 4. Javascript
> > 5. README.md file with explanation of the algorithm
> 
> Is golang acceptable?

@Anuragkar234 any language is acceptable, but these are preferred.

You can reopen your PR, and follow the [contribution guidelines](https://github.com/developer-student-club-thapar/algo-book/blob/master/CONTRIBUTING.md) given.

**Comment by DakshKK** [comment]
> do I fork right now or wait for someone to assign or one issue can only be assigned to one person?

@KuKikb please refer to the [contribution guidelines](https://github.com/developer-student-club-thapar/algo-book/blob/master/CONTRIBUTING.md), and follow them. There is no allotment, you can fork and implement. If yours is acceptable, and not duplicate, we merge it.

**Comment by Anuragkar234** [comment]
Added a PR, kindly check it out
