### ISSUE TITLE
Add Algo to check if number is Palindrome

### ISSUE THREAD

**Issue by pranavvidyarthi7** [developer-student-club-thapar/algo-book#59]
Here are the requirements for an acceptable PR for the same.
Languages for the algorithms:

1. - Python
2. - C++
3. - Java
4. - Javascript
5. - README.md file with explanation of the algorithm

**Comment by MRaahulVignesh** [comment]
Hey @pranavvidyarthi7, can I try this? I will be using python as the language.

**Comment by MRaahulVignesh** [comment]
Hey @pranavvidyarthi7, can I try this? I will be using python as the language.

**Comment by swaraj70** [comment]
Hi @pranavvidyarthi7! I would like to complete this using java.

**Comment by Abtaha** [comment]
Hey @pranavvidyarthi7! I want to do this task using C++

**Comment by pranavvidyarthi7** [comment]
sure 
@MRaahulVignesh : Python
@swaraj70 : Java
@Abtaha : C++
Apart from writing the code in respective languages, one of you can make the readme file too

**Comment by pranavvidyarthi7** [comment]
We already have a folder with template for readme

**Comment by Khush-Ramdev** [comment]
i would like to do this in javascript

**Comment by pranavvidyarthi7** [comment]
Sure @Khush-Ramdev
